on:
  # manual trigger
  workflow_call:
  push:
    branches:
    - badges
    # only trigger wihen change php files
    paths:
    - "**.php"
  pull_request:
    branches:
    - badges
    - master
    # only trigger wihen change php files
    paths:
    - "**.php"

name : 'Code Lint Global'

jobs:
  codeLintGlobal:
    # check official jeedom workflows
    # https://github.com/jeedom/workflows/tree/main/.github/workflows
    uses: jeedom/workflows/.github/workflows/codeLintGlobal.yml@main
