on:
  # Workflows check plugin Jeedom
  push:
    branches:
      - badges
  pull_request:
    branches:
      - beta
      - master
      
name : 'Test Plugin Jeedom'

jobs:
  codeLintGlobal:
    uses: jeedom/workflows/.github/workflows/codeLintGlobal.yml@main
