on:
  # Workflows check plugin Jeedom
  push:
    branches:
      - badges
  pull_request:
    branches:
      - beta
      - master
      
name : 'Test Plugin Jeedom'

jobs:
  php:
    uses: jeedom/workflows/.github/workflows/php.yml@main
