on:
  # Workflows check plugin Jeedom
  push:
    branches:
      - beta
  pull_request:
    branches:
      - beta
      - master
      
name : 'Test Plugin Jeedom'

jobs:
  codeLintGlobal:
    uses: jeedom/workflows/.github/workflows/codeLintGlobal.yml@main
  php73:
    uses: jeedom/workflows/.github/workflows/lint_Php73.yml@main
  php74:
    uses: jeedom/workflows/.github/workflows/lint_Php74.yml@main
  php:
    uses: jeedom/workflows/.github/workflows/php.yml@main
